sudo: false
 
language: node_js
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
 
cache:
  directories:
    - node_modules
 
before_script:
  - meteor npm install
 
script:
  - meteor npm install --save react react-dom
  - meteor npm install --save react-addons-pure-render-mixin
  - meteor add react-meteor-data
  - meteor add accounts-ui accounts-password
  - meteor remove insecure
  - meteor remove autopublish
  - meteor npm install --save classnames
  - meteor add practicalmeteor:mocha
  - meteor test --driver-package practicalmeteor:mocha